name: dietti_models
description: models
version: 0.0.1
homepage:

environment:
  sdk: ^3.0.0

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6